/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tesis;

/**
 *
 * @author gtroncone
 */

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    
    private JLabel etiquetaMapa;
    private MapRender render;
    private boolean zoomingH = false;
    private boolean zoomingV = false;
    
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapa = new javax.swing.JPanel();
        sliderV = new javax.swing.JSlider();
        sliderH = new javax.swing.JSlider();
        btnZoomIn = new javax.swing.JButton();
        btnZoomOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tesis");
        setPreferredSize(new java.awt.Dimension(1200, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 720));

        mapa.setName(""); // NOI18N

        javax.swing.GroupLayout mapaLayout = new javax.swing.GroupLayout(mapa);
        mapa.setLayout(mapaLayout);
        mapaLayout.setHorizontalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        mapaLayout.setVerticalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        sliderV.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderV.setPaintLabels(true);
        sliderV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVStateChanged(evt);
            }
        });

        sliderH.setPaintLabels(true);
        sliderH.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderHStateChanged(evt);
            }
        });

        btnZoomIn.setText("+");
        btnZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomInActionPerformed(evt);
            }
        });

        btnZoomOut.setText("-");
        btnZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sliderV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnZoomIn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnZoomOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderV, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(sliderH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnZoomIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnZoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderHStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderHStateChanged
        if (zoomingH) {
            sliderH.setValue(render.getX());
            zoomingH = false;
        } else {
            int valor = sliderH.getValue();
            render.setX(valor);
            actualizarMapa();
        }
    }//GEN-LAST:event_sliderHStateChanged

    private void sliderVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVStateChanged
        if (zoomingV) {
            sliderV.setValue(render.getY());
            zoomingV = false;
        } else {
            int valor = sliderV.getValue();
            render.setY(valor);
            actualizarMapa();
        }
    }//GEN-LAST:event_sliderVStateChanged

    private void btnZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomInActionPerformed
        if (render.getZoom() < render.getMetadata().getMaxZoom()) {
            render.aumentarZoom();
            actualizarMapa();
            zoomingV = true;
            zoomingH = true;
            actualizarSliders();
        }
    }//GEN-LAST:event_btnZoomInActionPerformed

    private void btnZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomOutActionPerformed
        if (render.getZoom() > render.getMetadata().getMinZoom()) {
            render.disminuirZoom();
            actualizarMapa();
            zoomingV = true;
            zoomingH = true;
            actualizarSliders();
        }
    }//GEN-LAST:event_btnZoomOutActionPerformed

    /**        this.dibujar(tiles.getRender(12, valor, 0));
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI tesis = new UI();
                tesis.setVisible(true);
                tesis.inicializar();
            }
        });
    }
    
    public void inicializar() {
        MapRender tiles = new MapRender();
        render = tiles;
        JLabel etiqueta = new JLabel(new ImageIcon(tiles.getRender()), JLabel.CENTER);
        etiquetaMapa = etiqueta;
        mapa.add(etiqueta);
        sliderH.setValue(0);
        sliderV.setValue(0);
        sliderH.setMaximum(render.getMetadata().getDato(render.getZoom(), "numX") - render.getNUM_X());
        sliderV.setInverted(true);
        sliderV.setMaximum(render.getMetadata().getDato(render.getZoom(), "numY") - render.getNUM_Y()); 
        etiqueta.setSize(new Dimension(render.getNUM_X() * render.getMetadata().getDimX(), 
                render.getNUM_Y() * render.getMetadata().getDimY()));
    }
    
    public void actualizarMapa() {
        etiquetaMapa.setIcon(new ImageIcon(render.getRender()));
    }
    
    public void actualizarSliders() {
        sliderH.setMaximum(render.getMetadata().getDato(render.getZoom(), "numX") - render.getNUM_X());
        sliderV.setMaximum(render.getMetadata().getDato(render.getZoom(), "numY") - render.getNUM_Y()); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZoomIn;
    private javax.swing.JButton btnZoomOut;
    private javax.swing.JPanel mapa;
    private javax.swing.JSlider sliderH;
    private javax.swing.JSlider sliderV;
    // End of variables declaration//GEN-END:variables
}
